### ISSUE TITLE
Save hang indefinitively with smartcut activated

### ISSUE THREAD

**Issue by sos-productions** [ozmartian/vidcutter-appimage#5]
Hello ozmartian,

I activated all the options except one : Smartcut which stalled the export.
on the trailer of Claws Of the Red Dragon (https://clawsofthereddragon.com/trailer/)
This documentary is for now freely watchable here
https://www.youtube.com/watch?v=Mg5budPRY1Q
and I want to clean the English subtitles video sections, I want to extract with your tool.
This is due of some error in python (I did not managed to build from source either on LMDE3) 

Here is the log:
====8<====================================
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - /tmp/.mount_VidCutA7ne7y/usr/bin/ffprobe -hide_banner -v error -show_packets -select_streams v -show_entries packet=pts_time,flags -of csv "/home/james/Documents/Vidcutter/video.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - -v error -ss 2.958333 -t 15.208334 -i "/home/james/Documents/Vidcutter/video.mp4" -c copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/home/james/Documents/Vidcutter/video_EDIT_00_middle_00.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - -v 32 -i "/home/james/Documents/Vidcutter/video.mp4" -ss 18.166667 -t 0.999333 -c:v libx264 -tune film -preset ultrafast -x264-params crf=23 -qp 0 -flags +cgop -c:a copy -c:s copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/home/james/Documents/Vidcutter/video_EDIT_00_end_00.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - -v 32 -i "/home/james/Documents/Vidcutter/video.mp4" -ss 19.208 -t 0.00033300000000124896 -c:v libx264 -tune film -preset ultrafast -x264-params crf=23 -qp 0 -flags +cgop -c:a copy -c:s copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/home/james/Documents/Vidcutter/video_EDIT_01_start_01.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - -v error -ss 21.208333 -t 3.0416670000000003 -i "/home/james/Documents/Vidcutter/video.mp4" -c copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/home/james/Documents/Vidcutter/video_EDIT_01_middle_01.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - -v 32 -i "/home/james/Documents/Vidcutter/video.mp4" -ss 24.25 -t 0.625 -c:v libx264 -tune film -preset ultrafast -x264-params crf=23 -qp 0 -flags +cgop -c:a copy -c:s copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/home/james/Documents/Vidcutter/video_EDIT_01_end_01.mp4"
2020-05-20 17:51 - root - CRITICAL -   File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 1363, in saveMedia
    self.smartcutter(file, source_file, source_ext)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 1413, in smartcutter
    allstreams=True)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 331, in smartcut
    bisections = self.getGOPbisections(source, start, end)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 590, in getGOPbisections
    end_pos = bisect_left(keyframes, end)

2020-05-20 17:51 - root - CRITICAL - <class 'TypeError'>: '<' not supported between instances of 'str' and 'float'
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': True, 'end': False}
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'start': True, 'middle': False, 'end': False}
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'start': True, 'middle': True, 'end': False}
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': True, 'end': True}
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - /tmp/.mount_VidCutA7ne7y/usr/bin/ffmpeg -hide_banner -i "/home/james/Documents/Vidcutter/video_EDIT_00_middle_00.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - cmd output: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/Documents/Vidcutter/video_EDIT_00_middle_00.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:18.29, start: 0.083000, bitrate: 4978 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 2560x1440, 4721 kb/s, 24 fps, 24 tbr, 90k tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 253 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
At least one output file must be specified
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - smartcut files are MPEG based so join via MPEG-TS
2020-05-20 17:51 - vidcutter.libs.videoservice - ERROR - Exception during MPEG-TS join
Traceback (most recent call last):
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 622, in mpegtsJoin
    name, _ = os.path.splitext(file)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3.6/posixpath.py", line 122, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - smartcut MPEG-TS join failed, retry with standard concat
2020-05-20 17:51 - root - CRITICAL -   File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 418, in smartcheck
    self.smartjoin(index)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 446, in smartjoin
    self.smartcut_jobs[index].allstreams, None)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 459, in join
    filelist = os.path.normpath(os.path.join(os.path.dirname(inputs[0]), '_vidcutter.list'))
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3.6/posixpath.py", line 156, in dirname
    p = os.fspath(p)

2020-05-20 17:51 - root - CRITICAL - <class 'TypeError'>: expected str, bytes or os.PathLike object, not NoneType
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'start': True, 'middle': True, 'end': True}
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - /tmp/.mount_VidCutA7ne7y/usr/bin/ffmpeg -hide_banner -i "/home/james/Documents/Vidcutter/video_EDIT_01_middle_01.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - cmd output: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/Documents/Vidcutter/video_EDIT_01_middle_01.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:05.14, start: 0.000000, bitrate: 6115 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 2560x1440, 5874 kb/s, 24 fps, 24 tbr, 90k tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 252 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
At least one output file must be specified
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - smartcut files are MPEG based so join via MPEG-TS
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - /tmp/.mount_VidCutA7ne7y/usr/bin/ffmpeg -hide_banner -i "/home/james/Documents/Vidcutter/video_EDIT_01_start_01.mp4"
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - cmd output: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/james/Documents/Vidcutter/video_EDIT_01_start_01.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:00.04, start: 0.000000, bitrate: 83003 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 2560x1440, 83514 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
At least one output file must be specified
2020-05-20 17:51 - vidcutter.libs.videoservice - ERROR - Exception during MPEG-TS join
Traceback (most recent call last):
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 619, in mpegtsJoin
    video_bsf, audio_bsf = self.getBSF(inputs[0])
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 491, in getBSF
    vcodec, acodec = self.codecs(source)
  File "/tmp/.mount_VidCutA7ne7y/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 268, in codecs
    acodec = re.search(r'Stream.*Audio:\s(\w+)', result).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - smartcut MPEG-TS join failed, retry with standard concat
2020-05-20 17:51 - vidcutter.libs.videoservice - INFO - /tmp/.mount_VidCutA7ne7y/usr/bin/ffmpeg -hide_banner -v error -f concat -safe 0 -i "/home/james/Documents/Vidcutter/_vidcutter.list" -c copy -map 0 -y "/home/james/Documents/Vidcutter/video_EDIT_01.mp4"
========8<===========================

[Claws of the Red Dragon—Official trailer_HD_HLS.vcp.txt](https://github.com/ozmartian/vidcutter-appimage/files/4658045/Claws.of.the.Red.Dragon.Official.trailer_HD_HLS.vcp.txt)
![Save_stalled](https://user-images.githubusercontent.com/25987872/82470764-0a959a00-9ac6-11ea-92eb-3feb2f020fd8.png)

**Comment by EJE-2** [comment]
I have the same issue in Ubuntu 20.04 LTS and am unable to use the program at all because it fails to save the media.  This program worked without issue on Ubuntu 18.04 LTS.

**Comment by dabesa** [comment]
Same here, I hope to hear back from Pete.

**Comment by ozmartian** [comment]
Try again with the latest version 6.0.5.1 from the PPA or Snap app. All updated from Ubuntu 20+.

**Comment by ozmartian** [comment]
No longer supporting AppImage. If on Ubuntu 20+ use the Launchpad PPA to install natively or the Snap/Flatpak apps all updated to version 6.0.5.1
